//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_IB120117.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IB120117Entities : DbContext
    {
        public IB120117Entities()
            : base("name=IB120117Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jela> Jela { get; set; }
        public virtual DbSet<Klijenti> Klijenti { get; set; }
        public virtual DbSet<Komentari> Komentari { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<NarudzbaStavke> NarudzbaStavke { get; set; }
        public virtual DbSet<Narudzbe> Narudzbe { get; set; }
        public virtual DbSet<Naselja> Naselja { get; set; }
        public virtual DbSet<NaseljaKlijenti> NaseljaKlijenti { get; set; }
        public virtual DbSet<Ocjene> Ocjene { get; set; }
        public virtual DbSet<Restorani> Restorani { get; set; }
        public virtual DbSet<Uloge> Uloge { get; set; }
        public virtual DbSet<VelicinaJela> VelicinaJela { get; set; }
        public virtual DbSet<VelicinaJelaTabela> VelicinaJelaTabela { get; set; }
        public virtual DbSet<VrsteJela> VrsteJela { get; set; }
    
        public virtual ObjectResult<AllJelaPretragaByNaziv_Result> AllJelaPretragaByNaziv(string naziv, Nullable<int> vrstaID, Nullable<int> restoranID)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("vrstaID", vrstaID) :
                new ObjectParameter("vrstaID", typeof(int));
    
            var restoranIDParameter = restoranID.HasValue ?
                new ObjectParameter("restoranID", restoranID) :
                new ObjectParameter("restoranID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllJelaPretragaByNaziv_Result>("AllJelaPretragaByNaziv", nazivParameter, vrstaIDParameter, restoranIDParameter);
        }
    
        public virtual ObjectResult<AllJelaPretragaByVrstaRestoran_Result> AllJelaPretragaByVrstaRestoran(Nullable<int> vrstaID, Nullable<int> restoranID)
        {
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("vrstaID", vrstaID) :
                new ObjectParameter("vrstaID", typeof(int));
    
            var restoranIDParameter = restoranID.HasValue ?
                new ObjectParameter("restoranID", restoranID) :
                new ObjectParameter("restoranID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllJelaPretragaByVrstaRestoran_Result>("AllJelaPretragaByVrstaRestoran", vrstaIDParameter, restoranIDParameter);
        }
    
        public virtual ObjectResult<esp_AllKlijenti_Result> esp_AllKlijenti()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllKlijenti_Result>("esp_AllKlijenti");
        }
    
        public virtual ObjectResult<esp_AllKomentariOcjene_Result> esp_AllKomentariOcjene()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllKomentariOcjene_Result>("esp_AllKomentariOcjene");
        }
    
        public virtual ObjectResult<esp_AllNarudzbe_Result> esp_AllNarudzbe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllNarudzbe_Result>("esp_AllNarudzbe");
        }
    
        public virtual ObjectResult<esp_AllNarudzbeDatumi_Result> esp_AllNarudzbeDatumi(Nullable<System.DateTime> datumOd, Nullable<System.DateTime> datumDo)
        {
            var datumOdParameter = datumOd.HasValue ?
                new ObjectParameter("datumOd", datumOd) :
                new ObjectParameter("datumOd", typeof(System.DateTime));
    
            var datumDoParameter = datumDo.HasValue ?
                new ObjectParameter("datumDo", datumDo) :
                new ObjectParameter("datumDo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllNarudzbeDatumi_Result>("esp_AllNarudzbeDatumi", datumOdParameter, datumDoParameter);
        }
    
        public virtual ObjectResult<esp_AllNarudzbeStatus_Result> esp_AllNarudzbeStatus(Nullable<bool> status)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllNarudzbeStatus_Result>("esp_AllNarudzbeStatus", statusParameter);
        }
    
        public virtual ObjectResult<esp_AllNarudzbeStavkeByNarudzba_Result> esp_AllNarudzbeStavkeByNarudzba(Nullable<int> narudzbaID)
        {
            var narudzbaIDParameter = narudzbaID.HasValue ?
                new ObjectParameter("NarudzbaID", narudzbaID) :
                new ObjectParameter("NarudzbaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllNarudzbeStavkeByNarudzba_Result>("esp_AllNarudzbeStavkeByNarudzba", narudzbaIDParameter);
        }
    
        public virtual ObjectResult<esp_AllNaselja_Result> esp_AllNaselja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllNaselja_Result>("esp_AllNaselja");
        }
    
        public virtual ObjectResult<esp_AllRestoraniByNaziv_Result> esp_AllRestoraniByNaziv(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllRestoraniByNaziv_Result>("esp_AllRestoraniByNaziv", nazivParameter);
        }
    
        public virtual ObjectResult<esp_AllRestoraniLista_Result> esp_AllRestoraniLista()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllRestoraniLista_Result>("esp_AllRestoraniLista");
        }
    
        public virtual int esp_deleteJelo(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_deleteJelo", jeloIDParameter);
        }
    
        public virtual int esp_deleteKomentari(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_deleteKomentari", jeloIDParameter);
        }
    
        public virtual int esp_deleteNarudzbaStavke(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_deleteNarudzbaStavke", jeloIDParameter);
        }
    
        public virtual int esp_deleteOcjeneJelo(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_deleteOcjeneJelo", jeloIDParameter);
        }
    
        public virtual int esp_deleteRestorani(Nullable<int> restoranID)
        {
            var restoranIDParameter = restoranID.HasValue ?
                new ObjectParameter("restoranID", restoranID) :
                new ObjectParameter("restoranID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_deleteRestorani", restoranIDParameter);
        }
    
        public virtual int esp_deleteRestoraniJela(Nullable<int> restoranID)
        {
            var restoranIDParameter = restoranID.HasValue ?
                new ObjectParameter("restoranID", restoranID) :
                new ObjectParameter("restoranID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_deleteRestoraniJela", restoranIDParameter);
        }
    
        public virtual int esp_deleteVelicinaJelaTabela(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_deleteVelicinaJelaTabela", jeloIDParameter);
        }
    
        public virtual ObjectResult<esp_desktopKorisnickoIme_Result> esp_desktopKorisnickoIme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_desktopKorisnickoIme_Result>("esp_desktopKorisnickoIme", usernameParameter);
        }
    
        public virtual ObjectResult<esp_HistorijaNarudzbi2_Result> esp_HistorijaNarudzbi2(Nullable<int> klijentID)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_HistorijaNarudzbi2_Result>("esp_HistorijaNarudzbi2", klijentIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_InsertKlijenti2(string ime, string prezime, string telefon, string adresa, string korisnickoIme, string lozinkaSalt, string lozinkaHash, Nullable<bool> status)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_InsertKlijenti2", imeParameter, prezimeParameter, telefonParameter, adresaParameter, korisnickoImeParameter, lozinkaSaltParameter, lozinkaHashParameter, statusParameter);
        }
    
        public virtual int esp_InsertKomentari1(Nullable<int> jeloID, Nullable<int> klijentID, Nullable<System.DateTime> datum, string komentar)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("klijentID", klijentID) :
                new ObjectParameter("klijentID", typeof(int));
    
            var datumParameter = datum.HasValue ?
                new ObjectParameter("datum", datum) :
                new ObjectParameter("datum", typeof(System.DateTime));
    
            var komentarParameter = komentar != null ?
                new ObjectParameter("komentar", komentar) :
                new ObjectParameter("komentar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_InsertKomentari1", jeloIDParameter, klijentIDParameter, datumParameter, komentarParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_InsertKorisnici(string ime, string prezime, string email, string telefon, string adresa, string korisnickoIme, string lozinkaSalt, string lozinkaHash, Nullable<int> ulogeID, Nullable<int> naseljeID)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var ulogeIDParameter = ulogeID.HasValue ?
                new ObjectParameter("ulogeID", ulogeID) :
                new ObjectParameter("ulogeID", typeof(int));
    
            var naseljeIDParameter = naseljeID.HasValue ?
                new ObjectParameter("naseljeID", naseljeID) :
                new ObjectParameter("naseljeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_InsertKorisnici", imeParameter, prezimeParameter, emailParameter, telefonParameter, adresaParameter, korisnickoImeParameter, lozinkaSaltParameter, lozinkaHashParameter, ulogeIDParameter, naseljeIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_InsertNaseljeKlijenti2(Nullable<int> naseljeID, Nullable<int> klijentID)
        {
            var naseljeIDParameter = naseljeID.HasValue ?
                new ObjectParameter("NaseljeID", naseljeID) :
                new ObjectParameter("NaseljeID", typeof(int));
    
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_InsertNaseljeKlijenti2", naseljeIDParameter, klijentIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_InsertRestorani(string naziv, string telefon, string mail, string adresa, Nullable<bool> aktivno, byte[] slika, byte[] slikaThumb, Nullable<int> korisnikID)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var aktivnoParameter = aktivno.HasValue ?
                new ObjectParameter("Aktivno", aktivno) :
                new ObjectParameter("Aktivno", typeof(bool));
    
            var slikaParameter = slika != null ?
                new ObjectParameter("Slika", slika) :
                new ObjectParameter("Slika", typeof(byte[]));
    
            var slikaThumbParameter = slikaThumb != null ?
                new ObjectParameter("SlikaThumb", slikaThumb) :
                new ObjectParameter("SlikaThumb", typeof(byte[]));
    
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_InsertRestorani", nazivParameter, telefonParameter, mailParameter, adresaParameter, aktivnoParameter, slikaParameter, slikaThumbParameter, korisnikIDParameter);
        }
    
        public virtual ObjectResult<esp_JelaByRestoranID_Result> esp_JelaByRestoranID(Nullable<int> restoranID)
        {
            var restoranIDParameter = restoranID.HasValue ?
                new ObjectParameter("restoranID", restoranID) :
                new ObjectParameter("restoranID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_JelaByRestoranID_Result>("esp_JelaByRestoranID", restoranIDParameter);
        }
    
        public virtual ObjectResult<esp_JelaByRestoranIDVrstaID_Result> esp_JelaByRestoranIDVrstaID(Nullable<int> restoranID, Nullable<int> vrstaID)
        {
            var restoranIDParameter = restoranID.HasValue ?
                new ObjectParameter("restoranID", restoranID) :
                new ObjectParameter("restoranID", typeof(int));
    
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("vrstaID", vrstaID) :
                new ObjectParameter("vrstaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_JelaByRestoranIDVrstaID_Result>("esp_JelaByRestoranIDVrstaID", restoranIDParameter, vrstaIDParameter);
        }
    
        public virtual ObjectResult<esp_JelaByRestoranIDVrstaIDNazivv_Result> esp_JelaByRestoranIDVrstaIDNazivv(Nullable<int> restoranID, Nullable<int> vrstaID, string naziv)
        {
            var restoranIDParameter = restoranID.HasValue ?
                new ObjectParameter("restoranID", restoranID) :
                new ObjectParameter("restoranID", typeof(int));
    
            var vrstaIDParameter = vrstaID.HasValue ?
                new ObjectParameter("vrstaID", vrstaID) :
                new ObjectParameter("vrstaID", typeof(int));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_JelaByRestoranIDVrstaIDNazivv_Result>("esp_JelaByRestoranIDVrstaIDNazivv", restoranIDParameter, vrstaIDParameter, nazivParameter);
        }
    
        public virtual ObjectResult<esp_JelaZaPretraguAll_Result> esp_JelaZaPretraguAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_JelaZaPretraguAll_Result>("esp_JelaZaPretraguAll");
        }
    
        public virtual int esp_JeloAdd(string naziv, string opis, Nullable<bool> aktivno, byte[] slika, byte[] slikaThumb, Nullable<int> korisnikID, Nullable<int> restoranID, Nullable<int> vrsteJelaID)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var opisParameter = opis != null ?
                new ObjectParameter("Opis", opis) :
                new ObjectParameter("Opis", typeof(string));
    
            var aktivnoParameter = aktivno.HasValue ?
                new ObjectParameter("Aktivno", aktivno) :
                new ObjectParameter("Aktivno", typeof(bool));
    
            var slikaParameter = slika != null ?
                new ObjectParameter("Slika", slika) :
                new ObjectParameter("Slika", typeof(byte[]));
    
            var slikaThumbParameter = slikaThumb != null ?
                new ObjectParameter("SlikaThumb", slikaThumb) :
                new ObjectParameter("SlikaThumb", typeof(byte[]));
    
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            var restoranIDParameter = restoranID.HasValue ?
                new ObjectParameter("RestoranID", restoranID) :
                new ObjectParameter("RestoranID", typeof(int));
    
            var vrsteJelaIDParameter = vrsteJelaID.HasValue ?
                new ObjectParameter("VrsteJelaID", vrsteJelaID) :
                new ObjectParameter("VrsteJelaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_JeloAdd", nazivParameter, opisParameter, aktivnoParameter, slikaParameter, slikaThumbParameter, korisnikIDParameter, restoranIDParameter, vrsteJelaIDParameter);
        }
    
        public virtual ObjectResult<esp_JeloByID_Result> esp_JeloByID(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_JeloByID_Result>("esp_JeloByID", jeloIDParameter);
        }
    
        public virtual ObjectResult<esp_JeloByJeloID_Result> esp_JeloByJeloID(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_JeloByJeloID_Result>("esp_JeloByJeloID", jeloIDParameter);
        }
    
        public virtual ObjectResult<esp_JeloByJeloID2_Result> esp_JeloByJeloID2(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_JeloByJeloID2_Result>("esp_JeloByJeloID2", jeloIDParameter);
        }
    
        public virtual int esp_JeloDelete(Nullable<int> korinskikID)
        {
            var korinskikIDParameter = korinskikID.HasValue ?
                new ObjectParameter("korinskikID", korinskikID) :
                new ObjectParameter("korinskikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_JeloDelete", korinskikIDParameter);
        }
    
        public virtual ObjectResult<esp_KlijentByidMobile_Result> esp_KlijentByidMobile(Nullable<int> klijentID)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_KlijentByidMobile_Result>("esp_KlijentByidMobile", klijentIDParameter);
        }
    
        public virtual ObjectResult<esp_KorisniciAll_Result> esp_KorisniciAll(Nullable<int> naselje)
        {
            var naseljeParameter = naselje.HasValue ?
                new ObjectParameter("naselje", naselje) :
                new ObjectParameter("naselje", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_KorisniciAll_Result>("esp_KorisniciAll", naseljeParameter);
        }
    
        public virtual ObjectResult<esp_KorisniciAllForGrid_Result> esp_KorisniciAllForGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_KorisniciAllForGrid_Result>("esp_KorisniciAllForGrid");
        }
    
        public virtual ObjectResult<esp_KorisnikByID_Result> esp_KorisnikByID(Nullable<int> korinskikID)
        {
            var korinskikIDParameter = korinskikID.HasValue ?
                new ObjectParameter("korinskikID", korinskikID) :
                new ObjectParameter("korinskikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_KorisnikByID_Result>("esp_KorisnikByID", korinskikIDParameter);
        }
    
        public virtual int esp_KorisnikDelete(Nullable<int> korinskikID)
        {
            var korinskikIDParameter = korinskikID.HasValue ?
                new ObjectParameter("korinskikID", korinskikID) :
                new ObjectParameter("korinskikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_KorisnikDelete", korinskikIDParameter);
        }
    
        public virtual ObjectResult<esp_LastJelo_Result> esp_LastJelo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_LastJelo_Result>("esp_LastJelo");
        }
    
        public virtual ObjectResult<esp_LastKlijent2_Result> esp_LastKlijent2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_LastKlijent2_Result>("esp_LastKlijent2");
        }
    
        public virtual ObjectResult<esp_Narudzba_Zadnja_Result> esp_Narudzba_Zadnja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Narudzba_Zadnja_Result>("esp_Narudzba_Zadnja");
        }
    
        public virtual int esp_NarudzbaStavke_Insert(Nullable<int> narudzbaID, Nullable<int> jeloID, Nullable<int> kolicina, Nullable<int> velicinaJelaID)
        {
            var narudzbaIDParameter = narudzbaID.HasValue ?
                new ObjectParameter("NarudzbaID", narudzbaID) :
                new ObjectParameter("NarudzbaID", typeof(int));
    
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("JeloID", jeloID) :
                new ObjectParameter("JeloID", typeof(int));
    
            var kolicinaParameter = kolicina.HasValue ?
                new ObjectParameter("Kolicina", kolicina) :
                new ObjectParameter("Kolicina", typeof(int));
    
            var velicinaJelaIDParameter = velicinaJelaID.HasValue ?
                new ObjectParameter("VelicinaJelaID", velicinaJelaID) :
                new ObjectParameter("VelicinaJelaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_NarudzbaStavke_Insert", narudzbaIDParameter, jeloIDParameter, kolicinaParameter, velicinaJelaIDParameter);
        }
    
        public virtual ObjectResult<esp_Narudzbe_DateOdDateDo_Result> esp_Narudzbe_DateOdDateDo(Nullable<int> klijentID, Nullable<bool> status, Nullable<System.DateTime> datumod, Nullable<System.DateTime> datumdo)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            var datumodParameter = datumod.HasValue ?
                new ObjectParameter("datumod", datumod) :
                new ObjectParameter("datumod", typeof(System.DateTime));
    
            var datumdoParameter = datumdo.HasValue ?
                new ObjectParameter("datumdo", datumdo) :
                new ObjectParameter("datumdo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Narudzbe_DateOdDateDo_Result>("esp_Narudzbe_DateOdDateDo", klijentIDParameter, statusParameter, datumodParameter, datumdoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> esp_Narudzbe_Insert(string brojNarudzbe, Nullable<int> klijentID, Nullable<System.DateTime> datum)
        {
            var brojNarudzbeParameter = brojNarudzbe != null ?
                new ObjectParameter("BrojNarudzbe", brojNarudzbe) :
                new ObjectParameter("BrojNarudzbe", typeof(string));
    
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            var datumParameter = datum.HasValue ?
                new ObjectParameter("Datum", datum) :
                new ObjectParameter("Datum", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("esp_Narudzbe_Insert", brojNarudzbeParameter, klijentIDParameter, datumParameter);
        }
    
        public virtual ObjectResult<esp_NaseljaAll_Result> esp_NaseljaAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_NaseljaAll_Result>("esp_NaseljaAll");
        }
    
        public virtual ObjectResult<esp_NaseljeByKlijentIDMobile_Result> esp_NaseljeByKlijentIDMobile(Nullable<int> klijentID)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_NaseljeByKlijentIDMobile_Result>("esp_NaseljeByKlijentIDMobile", klijentIDParameter);
        }
    
        public virtual ObjectResult<esp_NaseljeIDByKlijentID_Result> esp_NaseljeIDByKlijentID(Nullable<int> klijentID)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_NaseljeIDByKlijentID_Result>("esp_NaseljeIDByKlijentID", klijentIDParameter);
        }
    
        public virtual ObjectResult<esp_PodaciOKlijentuNarudzbeStavkeByNarudzba_Result> esp_PodaciOKlijentuNarudzbeStavkeByNarudzba(Nullable<int> narudzbaID)
        {
            var narudzbaIDParameter = narudzbaID.HasValue ?
                new ObjectParameter("NarudzbaID", narudzbaID) :
                new ObjectParameter("NarudzbaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_PodaciOKlijentuNarudzbeStavkeByNarudzba_Result>("esp_PodaciOKlijentuNarudzbeStavkeByNarudzba", narudzbaIDParameter);
        }
    
        public virtual ObjectResult<esp_RestoraniAll_Result> esp_RestoraniAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_RestoraniAll_Result>("esp_RestoraniAll");
        }
    
        public virtual ObjectResult<esp_RestoraniByID_Result> esp_RestoraniByID(Nullable<int> restoranID)
        {
            var restoranIDParameter = restoranID.HasValue ?
                new ObjectParameter("restoranID", restoranID) :
                new ObjectParameter("restoranID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_RestoraniByID_Result>("esp_RestoraniByID", restoranIDParameter);
        }
    
        public virtual int esp_SetIsporuceno(Nullable<int> narudzbaID)
        {
            var narudzbaIDParameter = narudzbaID.HasValue ?
                new ObjectParameter("NarudzbaID", narudzbaID) :
                new ObjectParameter("NarudzbaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_SetIsporuceno", narudzbaIDParameter);
        }
    
        public virtual ObjectResult<esp_UlogeAll_Result> esp_UlogeAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_UlogeAll_Result>("esp_UlogeAll");
        }
    
        public virtual int esp_UpadateNaseljaKlijenti(Nullable<int> naseljaKlijenti, Nullable<int> klijentID, Nullable<int> naseljeID)
        {
            var naseljaKlijentiParameter = naseljaKlijenti.HasValue ?
                new ObjectParameter("NaseljaKlijenti", naseljaKlijenti) :
                new ObjectParameter("NaseljaKlijenti", typeof(int));
    
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            var naseljeIDParameter = naseljeID.HasValue ?
                new ObjectParameter("NaseljeID", naseljeID) :
                new ObjectParameter("NaseljeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_UpadateNaseljaKlijenti", naseljaKlijentiParameter, klijentIDParameter, naseljeIDParameter);
        }
    
        public virtual int esp_UpdateKlijenti(Nullable<int> klijentID, string ime, string prezime, string adresa, string telefon, string korisnickoIme, string lozinkaSalt, string lozinkaHash, Nullable<bool> status)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_UpdateKlijenti", klijentIDParameter, imeParameter, prezimeParameter, adresaParameter, telefonParameter, korisnickoImeParameter, lozinkaSaltParameter, lozinkaHashParameter, statusParameter);
        }
    
        public virtual ObjectResult<esp_VelicinaJelaAll_Result> esp_VelicinaJelaAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_VelicinaJelaAll_Result>("esp_VelicinaJelaAll");
        }
    
        public virtual ObjectResult<esp_VelicinaJelaByJeloID_Result> esp_VelicinaJelaByJeloID(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_VelicinaJelaByJeloID_Result>("esp_VelicinaJelaByJeloID", jeloIDParameter);
        }
    
        public virtual int esp_VelicineJelaTableInsert(Nullable<decimal> cijena, Nullable<int> velicinaJelaID, Nullable<int> jeloID)
        {
            var cijenaParameter = cijena.HasValue ?
                new ObjectParameter("Cijena", cijena) :
                new ObjectParameter("Cijena", typeof(decimal));
    
            var velicinaJelaIDParameter = velicinaJelaID.HasValue ?
                new ObjectParameter("VelicinaJelaID", velicinaJelaID) :
                new ObjectParameter("VelicinaJelaID", typeof(int));
    
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("JeloID", jeloID) :
                new ObjectParameter("JeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_VelicineJelaTableInsert", cijenaParameter, velicinaJelaIDParameter, jeloIDParameter);
        }
    
        public virtual ObjectResult<esp_VrsteJelaAll_Result> esp_VrsteJelaAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_VrsteJelaAll_Result>("esp_VrsteJelaAll");
        }
    
        public virtual ObjectResult<KlijentByKorisnickoIme1_Result> KlijentByKorisnickoIme1(string korisnickoIme)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KlijentByKorisnickoIme1_Result>("KlijentByKorisnickoIme1", korisnickoImeParameter);
        }
    
        public virtual ObjectResult<PreporukaRestorana_Result> PreporukaRestorana(Nullable<int> jeloID)
        {
            var jeloIDParameter = jeloID.HasValue ?
                new ObjectParameter("jeloID", jeloID) :
                new ObjectParameter("jeloID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PreporukaRestorana_Result>("PreporukaRestorana", jeloIDParameter);
        }
    
        public virtual int usp_UpdateKorisnici(Nullable<int> korisnikID, string ime, string prezime, string email, string telefon, string adresa, string korisnickoIme, string lozinkaSalt, string lozinkaHash, Nullable<bool> status, Nullable<int> ulogaID, Nullable<int> naseljeID)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var ulogaIDParameter = ulogaID.HasValue ?
                new ObjectParameter("UlogaID", ulogaID) :
                new ObjectParameter("UlogaID", typeof(int));
    
            var naseljeIDParameter = naseljeID.HasValue ?
                new ObjectParameter("naseljeID", naseljeID) :
                new ObjectParameter("naseljeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateKorisnici", korisnikIDParameter, imeParameter, prezimeParameter, emailParameter, telefonParameter, adresaParameter, korisnickoImeParameter, lozinkaSaltParameter, lozinkaHashParameter, statusParameter, ulogaIDParameter, naseljeIDParameter);
        }
    
        public virtual int usp_UpdateKorisnikAktivnost(Nullable<int> korisnikID, Nullable<bool> aktivnost)
        {
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            var aktivnostParameter = aktivnost.HasValue ?
                new ObjectParameter("Aktivnost", aktivnost) :
                new ObjectParameter("Aktivnost", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateKorisnikAktivnost", korisnikIDParameter, aktivnostParameter);
        }
    
        public virtual ObjectResult<esp_AllNarudzbeStatusDatumi_Result> esp_AllNarudzbeStatusDatumi(Nullable<System.DateTime> datumOd, Nullable<System.DateTime> datumDo, Nullable<bool> status)
        {
            var datumOdParameter = datumOd.HasValue ?
                new ObjectParameter("datumOd", datumOd) :
                new ObjectParameter("datumOd", typeof(System.DateTime));
    
            var datumDoParameter = datumDo.HasValue ?
                new ObjectParameter("datumDo", datumDo) :
                new ObjectParameter("datumDo", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_AllNarudzbeStatusDatumi_Result>("esp_AllNarudzbeStatusDatumi", datumOdParameter, datumDoParameter, statusParameter);
        }
    
        public virtual ObjectResult<esp_Narudzbe_DateOdDateDoREPORT_Result> esp_Narudzbe_DateOdDateDoREPORT(Nullable<int> klijentID, Nullable<bool> status, Nullable<System.DateTime> datumod, Nullable<System.DateTime> datumdo)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            var datumodParameter = datumod.HasValue ?
                new ObjectParameter("datumod", datumod) :
                new ObjectParameter("datumod", typeof(System.DateTime));
    
            var datumdoParameter = datumdo.HasValue ?
                new ObjectParameter("datumdo", datumdo) :
                new ObjectParameter("datumdo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Narudzbe_DateOdDateDoREPORT_Result>("esp_Narudzbe_DateOdDateDoREPORT", klijentIDParameter, statusParameter, datumodParameter, datumdoParameter);
        }
    
        public virtual ObjectResult<esp_PodaciOKlijentuNarudzbeStavkeByNarudzba1_Result> esp_PodaciOKlijentuNarudzbeStavkeByNarudzba1(Nullable<int> narudzbaID)
        {
            var narudzbaIDParameter = narudzbaID.HasValue ?
                new ObjectParameter("NarudzbaID", narudzbaID) :
                new ObjectParameter("NarudzbaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_PodaciOKlijentuNarudzbeStavkeByNarudzba1_Result>("esp_PodaciOKlijentuNarudzbeStavkeByNarudzba1", narudzbaIDParameter);
        }
    }
}
