//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_IB120117.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzbe()
        {
            this.NarudzbaStavke = new HashSet<NarudzbaStavke>();
        }
    
        public int NarudzbaID { get; set; }
        public string BrojNarudzbe { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Otkazana { get; set; }
        public int KlijentID { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudzbaStavke> NarudzbaStavke { get; set; }
    }
}
