//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_IB120117.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaseljaKlijenti
    {
        public int NaseljaKlijentiID { get; set; }
        public Nullable<int> NaseljeID { get; set; }
        public Nullable<int> KlijentID { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        public virtual Naselja Naselja { get; set; }
    }
}
