//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_IB120117.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VelicinaJelaTabela
    {
        public int VelicinaJelaTabelaID { get; set; }
        public Nullable<decimal> Cijena { get; set; }
        public int VelicinaJelaID { get; set; }
        public int JeloID { get; set; }
    
        public virtual Jela Jela { get; set; }
        public virtual VelicinaJela VelicinaJela { get; set; }
    }
}
